[server]
headless = true
runOnSave = false
fileWatcherType = "none"
enableWebsocketCompression = true
websocketPingInterval = 20
disconnectedSessionTTL = 300

[runner]
fastReruns = true

[browser]
gatherUsageStats = false
